-- vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { desc = "Goto Declaration" })
-- vim.keymap.set("n", "gd", "<cmd> Telescope lsp_definitions<CR>", { desc = "Goto Definition" })
-- if vim.bo.filetype ~= "rust" then
-- 	vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Hover" })
-- end
-- vim.keymap.set("n", "<leader>gi", "<cmd> Telescope lsp_implementations<CR>", { desc = "Show Implementations" })
--
-- vim.keymap.set("n", "<leader>wl", function()
-- 	print(vim.inspect(vim.lsp.buf.list_workleader_folders()))
-- end, { desc = "List Workleader Folders" })
-- vim.keymap.set("n", "<leader>D", vim.lsp.buf.type_definition, { desc = "Goto Type Definition" })
-- vim.keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, { desc = "Code Action" })
-- vim.keymap.set("n", "gr", "<cmd> Telescope lsp_references<CR>", { desc = "Show References" })
-- vim.keymap.set("n", "<leader>f", function()
-- 	vim.lsp.buf.format({})
-- end, { desc = "Format" })
